# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .azure_web_app import *
from .provider import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "AzureWebapp",
  "mod": "index",
  "fqn": "pulumi_AzureWebapp",
  "classes": {
   "x:index:AzureWebApp": "AzureWebApp"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "AzureWebapp",
  "token": "pulumi:providers:AzureWebapp",
  "fqn": "pulumi_AzureWebapp",
  "class": "Provider"
 }
]
"""
)
